version: '3.8'

services:
  # 1. The Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: careersync_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=careersync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Cache (Redis)
  cache:
    image: redis:7-alpine
    container_name: careersync_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# This tells Docker to save the data so you don't lose it
volumes:
  postgres_data:
  redis_data: